const bcrypt = require('bcryptjs');

async function getUsers() {
  const defaultPasswordHash = await bcrypt.hash('Travel@12345', 10);
  const adminPasswordHash = await bcrypt.hash(process.env.ADMIN_PASSWORD || 'Admin@12345', 10);

  return [
    {
      fullName: process.env.ADMIN_NAME || 'Admin User',
      email: (process.env.ADMIN_EMAIL || 'admin@tripshare.in').toLowerCase(),
      phone: process.env.ADMIN_PHONE || '9999999999',
      city: 'Delhi',
      password: adminPasswordHash,
      role: 'admin',
      bio: 'TripShare India Community Lead & Alpine Trekker. Explorer of high mountain passes and coastal highways.',
      profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      travelStyle: 'Adventure',
      interests: ['Mountains', 'Trekking', 'Road Trips', 'Photography'],
      budgetLevel: 'Moderate',
      adventureLevel: 'High',
      accommodationPref: 'Homestays',
      transportPref: 'Self-Drive / Bikes',
      groupPreference: 'Small Group',
      destinationsVisited: ['Ladakh', 'Spiti Valley', 'Goa', 'Rishikesh'],
      bucketList: ['Meghalaya', 'Zanskar', 'Andaman'],
      verified: true
    },
    {
      fullName: 'Arjun Mehta',
      email: 'arjun@tripshare.in',
      phone: '9820112233',
      city: 'Delhi',
      password: defaultPasswordHash,
      bio: 'High-altitude motorbike tourer & landscape photographer. 14 Himalayan passes crossed and counting.',
      profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
      travelStyle: 'Roadtripper',
      interests: ['Mountains', 'Road Trips', 'Photography', 'Camping', 'Trekking'],
      budgetLevel: 'Moderate',
      adventureLevel: 'High',
      accommodationPref: 'Camps',
      transportPref: 'Self-Drive / Bikes',
      groupPreference: 'Small Group',
      destinationsVisited: ['Ladakh', 'Manali', 'Spiti Valley', 'Rajasthan'],
      bucketList: ['Zanskar', 'Tawang', 'Kashmir'],
      verified: true
    },
    {
      fullName: 'Riya Sharma',
      email: 'riya@tripshare.in',
      phone: '9833221100',
      city: 'Mumbai',
      password: defaultPasswordHash,
      bio: 'Solo female traveler & food explorer. Always in search of hidden cafes, coastal sunsets, and heritage alleys.',
      profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
      travelStyle: 'Solo Explorer',
      interests: ['Beaches', 'Food', 'Culture', 'Photography', 'Heritage'],
      budgetLevel: 'Moderate',
      adventureLevel: 'Moderate',
      accommodationPref: 'Hostels',
      transportPref: 'Public / Trains',
      groupPreference: 'Solo',
      destinationsVisited: ['Goa', 'Udaipur', 'Kochi', 'Pondicherry'],
      bucketList: ['Meghalaya', 'Varanasi', 'Hampi'],
      verified: true
    },
    {
      fullName: 'Vikram Sen',
      email: 'vikram@tripshare.in',
      phone: '9711884422',
      city: 'Bengaluru',
      password: defaultPasswordHash,
      bio: 'Tech lead by weekday, trail runner and mountaineer by weekend. Passionate about sustainable eco-tourism.',
      profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
      travelStyle: 'Adventure',
      interests: ['Mountains', 'Trekking', 'Wildlife', 'Camping', 'Backpacking'],
      budgetLevel: 'Comfort',
      adventureLevel: 'Extreme',
      accommodationPref: 'Homestays',
      transportPref: 'Shared Cabs',
      groupPreference: 'Small Group',
      destinationsVisited: ['Coorg', 'Wayanad', 'Himachal Pradesh', 'Sikkim'],
      bucketList: ['Ladakh', 'Spiti Valley', 'Valley of Flowers'],
      verified: true
    },
    {
      fullName: 'Ananya Iyer',
      email: 'ananya@tripshare.in',
      phone: '9845012345',
      city: 'Pune',
      password: defaultPasswordHash,
      bio: 'Architecture student documenting ancient stepwells, temple carvings, and indigenous artisan communities across India.',
      profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      travelStyle: 'Cultural',
      interests: ['Culture', 'Heritage', 'Spiritual', 'Photography', 'Food'],
      budgetLevel: 'Budget',
      adventureLevel: 'Moderate',
      accommodationPref: 'Homestays',
      transportPref: 'Public / Trains',
      groupPreference: 'Small Group',
      destinationsVisited: ['Jaipur', 'Varanasi', 'Madurai', 'Hampi'],
      bucketList: ['Kashmir', 'Khajuraho', 'Bhubaneswar'],
      verified: true
    },
    {
      fullName: 'Kabir Thapar',
      email: 'kabir@tripshare.in',
      phone: '9810054321',
      city: 'Chandigarh',
      password: defaultPasswordHash,
      bio: 'Lifelong backpacker. Love setting up camp under star-studded Himalayan skies and cooking over bonfire.',
      profileImage: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
      travelStyle: 'Backpacker',
      interests: ['Mountains', 'Backpacking', 'Camping', 'Trekking', 'Nightlife'],
      budgetLevel: 'Budget',
      adventureLevel: 'High',
      accommodationPref: 'Camps',
      transportPref: 'Public / Trains',
      groupPreference: 'Any',
      destinationsVisited: ['Manali', 'Kasol', 'Dharamshala', 'Rishikesh'],
      bucketList: ['Spiti Valley', 'Ladakh', 'Meghalaya'],
      verified: true
    },
    {
      fullName: 'Meera Nambiar',
      email: 'meera@tripshare.in',
      phone: '9847123987',
      city: 'Kochi',
      password: defaultPasswordHash,
      bio: 'Writer and marine enthusiast. Captivated by Kerala backwaters, Andaman reefs, and silent coastal coves.',
      profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
      travelStyle: 'Cultural',
      interests: ['Beaches', 'Culture', 'Wildlife', 'Food', 'Photography'],
      budgetLevel: 'Comfort',
      adventureLevel: 'Moderate',
      accommodationPref: 'Boutique Hotels',
      transportPref: 'Flights',
      groupPreference: 'Small Group',
      destinationsVisited: ['Kerala Backwaters', 'Goa', 'Andaman', 'Gokarna'],
      bucketList: ['Kashmir', 'Rajasthan', 'Ladakh'],
      verified: true
    },
    {
      fullName: 'Rohan Kapoor',
      email: 'rohan@tripshare.in',
      phone: '9928099112',
      city: 'Jaipur',
      password: defaultPasswordHash,
      bio: 'Desert safari explorer & vintage car restorer. Passionate about road-tripping through the Thar and Aravalis.',
      profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
      travelStyle: 'Roadtripper',
      interests: ['Road Trips', 'Heritage', 'Culture', 'Camping', 'Food'],
      budgetLevel: 'Moderate',
      adventureLevel: 'Moderate',
      accommodationPref: 'Homestays',
      transportPref: 'Self-Drive / Bikes',
      groupPreference: 'Small Group',
      destinationsVisited: ['Jaisalmer', 'Udaipur', 'Jodhpur', 'Pushkar'],
      bucketList: ['Spiti Valley', 'Ladakh', 'Meghalaya'],
      verified: true
    }
  ];
}

module.exports = { getUsers };
